### ISSUE TITLE
iOS 5.1.1 support

### ISSUE THREAD

**Issue by dvkch** [MPGNotification/MPGNotification#30]
Hi,

I would like to know if you would agree to support iOS 5.1.1. AFAIK it would only require you to modify a single line of code, the one referring to `NSFontAttributeName` by using the current implementation only if the iOS min required version is at least iOS 6.0, and adding a fallback for the other case.

I know not much people still support iOS5 but I would really appreciate if you could do this little modification.

Thanks for considering!

**Comment by toblerpwn** [comment]
Hi @dvkch !

Committing to iOS 5.x support would slow down future progress of the project, but, if this is important to you, please make a fork and add your own support!

If this is the only change you need to make, then pulling future changes from this repo should be a very easy operation for you. Also be sure to 'Watch' this repo for future changes if you maintain your own fork.

Good luck!

-sean

**Comment by dvkch** [comment]
That was my second option though it requires more work than sending a simple PR. Thanks anyway and keep up the good work! :)

**Comment by dvkch** [comment]
If anyone looks for this here it is: https://github.com/dvkch/MPGNotification/commit/6e71db61f096cd58119ecf688b7e839753d9d6ca
