### ISSUE TITLE
any way to get a handler to fire if the user *ignores* the notificaiton?

### ISSUE THREAD

**Issue by wdcurry** [MPGNotification/MPGNotification#37]
We can easily snag the tap of the notif, but not the ignore. This is crucial for in-app processing of received notifications via push as they insist we manage the 

Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

issues. The response must properly await the user tapping a message to act accordingly, and if ignored, then we act in a differing way.

**Comment by toblerpwn** [comment]
@wdcurry - I believe this is already supported by the `dismissHandler` property. see the `.h` file:

```
// Sets the dismiss hanlder block directly;
@property (nonatomic, copy) MPGNotificationDismissHandler dismissHandler;
```

This should fire in any type of dismissal - whether by timer, or swipe-away, or button-press, or tap. Please re-open and clarify if I'm misunderstanding. Thanks!
