### ISSUE TITLE
iconImage has no padding

### ISSUE THREAD

**Issue by chrisjrex** [MPGNotification/MPGNotification#39]
The `iconImage` has no padding and because the `iconImageView` is not exposed I can't edit its content mode.

* Solution 1:
Set the default mode to __UIViewContentModeCenter__. Then it adds padding to the image. 

```
- (void)setIconImage:(UIImage *)iconImage {
    
    _iconImage = iconImage;
    
    if (!self.iconImageView) {
        self.iconImageView = [[UIImageView alloc] initWithFrame:CGRectZero];
        [self.iconImageView setContentMode:UIViewContentModeCenter];
        [self.backgroundView addSubview:self.iconImageView];
    }
    
    self.iconImageView.image = iconImage;
    [self setNeedsLayout];
} 
```

* Solution 2:
Expose the image view or have a method to set the content mode you want.

**Comment by toblerpwn** [comment]
hi @chrisjrex - this is fixed in 6bcaaca8da147f85a2f54bbc3515fcd2f6f49b9e. I'm not sure when this issue got introduced (or maybe it was missed in testing somehow?), but there is now the expected (5px) padding before the text / trailing the icon image.
